### ISSUE TITLE
non-Java implementations of argument markers

### ISSUE THREAD

**Issue by bmoylan** [palantir/conjure#612]
Markers are currently impossible to implement in other languages. The [documentation](https://github.com/palantir/conjure/blob/master/docs/spec/conjure_definitions.md#argumentdefinition) says:

> List of types that serve as additional metadata for the argument. If the value of the field is a string it MUST be a type name that exists within the Conjure definition.

In conjure-java, `markers` on endpoint parameters are interpreted as annotations on method arguments. The most common use case is to mark arguments safe for logging.

I'd argue the spec is overfit to the java implementation. Even if we did have some form of annotation, these are always external types since conjure does not allow defining new annotations. Conjure only supports a `java` key for external types, so there's not really a path forward in other languages.

In conjure-go we'd like to be able to mark arguments safe, but go does not have a similar annotation construct for which there exist discrete types that can be imported into a definition. For example, witchcraft-go-server's endpoint registration uses option parameters like [`wrouter.SafePathParams`](https://pkg.go.dev/github.com/palantir/witchcraft-go-server/wrouter?tab=doc#SafePathParams) to indicate parameter safety.

Are there other markers in use anywhere? Should safety become a first-class concept so language implementations can decide how to deal with them independently?

**Comment by sfackler** [comment]
In conjure-rust, we look for exactly the java key `com.palantir.logsafe.Safe`, which is pretty jank: https://github.com/palantir/conjure-rust/blob/master/conjure-codegen/src/context.rs#L948-L957

**Comment by ferozco** [comment]
Hey @bmoylan, totally agree with your observation that the current IR overfits to the Java implementation. @carterkozak and I have discussed changing the IR so markers are an enum instead of a `Type` allowing us to express some shared concepts (ex: `safe`) while also permitting experimentation/language specific markers via the unknown variant. 

We have been pretty hesitant to make breaking change to the conjure IR since we've never done it before and to be frank because the work is easily de-prioritized since it doesn't necessarily improve things for the Java ecosystem. 

I think that this proposal (and other similar ones) would really benefit from collaboration between the different Conjure language maintainers so that incentives are better aligned to ensure we make progress while also adding more varied perspectives so we end up with a solution that works for everyone. Would you @bmoylan @sfackler be interested in contributing to make such a change happen?
